baseurl = "/"
languageCode = "en-us"
title = "Edgar's Data Lab"
theme = "slate"
features = ["responsive", "thumbnail", "syntax highlight", "structured data", "ogp", "twitter cards"]
googleAnalytics = "UA-108242418-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    name = "GitHub"
    url = "https://github.com/edgararuiz/"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/edgararuiz/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/theotheredgar/"


[params]
    description = "A website built through Hugo and blogdown."
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
[[ params.nav ]]
name = "Server"
tag = "admins"
icon = "server"

[[ params.nav ]]
name = "business"
tag = "business"
icon = "black-tie"

[[ params.nav ]]
name = "visualizations"
tag = "visualizations"
icon = "bar-chart"

[[ params.nav ]]
name = "Guides"
tag = "guides"
icon = "list-alt"

[[ params.nav ]]
name = "Webinars"
tag = "webinars"
icon = "film"

[[ params.nav ]]
name = "Presentations"
tag = "presentations"
icon = "group"

[[ params.nav ]]
name = "Español"
tag = "espanol"
icon = "group"

